---
- name: Simple Ansible Script Tower
  hosts: all
  become: yes
  gather_facts: no

  tasks:
  
    - name: Run shell
      shell: "{{ admin_commands }}"
      register: shell_result
      
    - name: Output result
      debug:
        msg: "{{ shell_result.stdout }}"
